language: python
python:
  - "3.6"
  - "3.7"
env:
  - DJANGO=2.0
  - DJANGO=2.1
  - DJANGO=2.2
  - DJANGO=3.0
install:
  - pip install -q Django==$DJANGO
  - pip install pep8
  - pip install pyflakes
before_script:
  - "pep8 --ignore=E128,E501 templated_email"
#  - "pyflakes templated_email"
script:
  - python manage.py test
